# Generated by Django 3.2 on 2022-11-25 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ebook',
            name='favorite',
            field=models.BooleanField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='ebook',
            name='genre',
        ),
        migrations.AlterField(
            model_name='ebook',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='Ebook_App.author'),
        ),
        migrations.AddField(
            model_name='ebook',
            name='genre',
            field=models.ManyToManyField(related_name='books', to='Ebook_App.Genre'),
        ),
    ]
