# Generated by Django 3.2 on 2022-11-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ebook_App', '0002_auto_20221125_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebook',
            name='favorite',
            field=models.BooleanField(default='False', max_length=50),
        ),
    ]
